proofing trello article
jaljo/articles pull request #13
Opened 2019-06-27 08:02 UTC by jaljo

2019-06-27 08:32 UTC, jaljo commented on trello-history/trello-history.md
> +[KNP History Power-up service](https://knp-trello-extension.glitch.me/)
Change that URL to the production one before merging

2019-06-29 14:56 UTC, fabschurt requested changes

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +If you've been working for a few years in software development, you're aware
```suggestion
If you've been working in software development for a few years, you're aware
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +that even before architectural or implementation decisions, to define what your
```suggestion
that even before architectural or implementation decisions, defining what your
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +client really **needs** stays on top of every project challenge. Let's imagine
```suggestion
client really **needs** stays on top of every project's challenges. Let's imagine
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +In an agile project's workflow, there is a chance some of these steps will
```suggestion
In an agile project's workflow, chances are that some of these steps will
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +2. you write the feature definition down this card,
Pourquoi avoir viré la préposition ici? Ça change le sens de la phrase et je crois que le sens original était le bon…

```suggestion
2. you write the feature definition down in this card,
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  3. you play poker with your teammates to give this card an estimation,
```suggestion
3. you play planning poker with your teammates to give this card an estimation,
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  4. you work the hell out of your sweat and blood to get the job done,
Je ne suis pas certain mais il me semble que cette expression n’est pas très idiomatique, je me demande même si c’est grammaticalement correct. Je propose l’alternative suivante, davantage éprouvée:

```suggestion
4. you work your ass off to get the job done,
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  expatriating yourself in the Loir-Et-Cher.
```suggestion
relocating to Loir-et-Cher.
```

Par ailleurs, la blague sur le Loir-et-Cher est drôle pour un francophone, par contre pas sûr que ça parle à un anglophone (et vu que l’article est en anglais…), mais bon, c’est pas forcément évident de trouver un équivalent plus universel, j’en conviens, donc au pire ça passe.

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  This little story brought to light the emergency for us to keep the history of
```suggestion
This little story brought to light the urgent need for us to log the history of
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +surreptitiously changed that card description.
```suggestion
surreptitiously changed that card's description.
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +written using traditional browser side web technologies (HTML, CSS, JS). So we
```suggestion
written using traditional browser-side web technologies (HTML, CSS, JS). So we
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  - Access a card history,
```suggestion
- access a card history,
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  good old XmlHttpRequest. To be called, the API requires explicit authentication:
```suggestion
good old XmlHttpRequest. In order to be called, the API requires explicit authentication:
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  1. An auto generated API key,
```suggestion
1. an auto-generated API key,
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +of the API key identified user.
```suggestion
of the API key-identified user.
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +dealing with asynchronicity. Indeed, the Trello API only let us perform actions
```suggestion
dealing with asynchronicity. Indeed, the Trello API only lets us perform actions
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +on domain oriented objects (card, boards, members...). That is, we still had no
```suggestion
on domain-oriented objects (card, boards, members…); that is: we still had no
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +Although this first version quite worked well, it also had several drawbacks.
```suggestion
Although this first version worked quite well, it also had several drawbacks.
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +way to directly interact with the Trello front application, nor to listen for
```suggestion
way to directly interact with the Trello front application, nor could we listen for
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +We considered to get around this problem by observing
```suggestion
We considered getting around this problem by observing
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +and detect when a specific element entered the DOM, identified by its class or
```suggestion
and detecting when a specific element entered the DOM, identified by its class or
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  id. Oh listen, what's that sound ? It looks like the WTF alarms are ranging
```suggestion
ID. Oh listen, what's that sound ? It sounds like the WTF alarms are ranging
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  what they so called [Power ups](https://trello.com/power-ups). See them as
```suggestion
their so-called [Power ups](https://trello.com/power-ups). You can see them as
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +external libraries which communicate with third services like Google, Facebook
```suggestion
external libraries which communicate with third-party services like Google, Facebook
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  **Capabilities are set in the Trello Power-ups administration board. Notice only
```suggestion
**Capabilities are set in the Trello Power-ups administration board. Please note that only
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +HTTPS, which can be a bit tricky when working in development environment.
```suggestion
HTTPS, which can be a bit tricky when working in a development environment.
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +purpose. So all we had to do was to create a new project from the
```suggestion
purposes. So all we had to do was to create a new project from the
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +lets you expose any local server to the Internet, which was handy for testing
```suggestion
lets you expose any local server to the Internet, which was handy for our testing
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +gracefully proposed by Trello and remix it to create our own service. This
```suggestion
graciously offered by Trello and remix it to create our own service. This
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +Of course, accessing a card history could have been achieved in many another
```suggestion
Of course, accessing a card's history could have been achieved in many other
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +way, by connecting Trello to Slack for example. That said, we liked the idea not
```suggestion
ways: by connecting Trello to Slack for example. That said, we liked the idea of not
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +to depend on another service and to have an "out of the box" solution that would
```suggestion
depending on another service and having an "out of the box" solution that would
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +to build power ups with it. Although their documentation is pretty huge,
Généralement _huge_ est plutôt réservé aux objets physiques il me semble.

```suggestion
to build power ups with it. Although their documentation is pretty sizable,
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  informations are sometime scattered, tedious to find and lacks of complete
_Information_ est un indénombrable en anglais.

```suggestion
information is sometimes scattered, tedious to find and lacks complete
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +ups were released in late 2018), and we learned it the hard way when we faced
```suggestion
ups were released as of late 2018), and we learned it the hard way when we faced
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +Speaking of which, know that once acquired, Trello will save the authentication
```suggestion
Speaking of which, please note that once the auth token is obtained, Trello will save it
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +token **server side**. If you're facing authentication problems or weird
```suggestion
**server-side**. If you're facing authentication problems or weird
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +behaviors, cleaning cookies or the cache browser side is not of any help.
```suggestion
behavior, cleaning cookies or the browser-side cache won't be of any help.
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +We almost went nuts because of this, until we found there was a special button
```suggestion
We almost went nuts because of this, until we found out there was a special button
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +architecture, but maybe it will worth to have a look on an FRP implementation
```suggestion
architecture, but it may be worth giving a try to an FRP implementation
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +with React and Redux. We're also considering to release this power up to the
```suggestion
with React and Redux. We're also considering releasing this power up to the
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +- host the [docker image of the project](https://cloud.docker.com/u/knplabs/repository/docker/knplabs/trello-history-powerup)
```suggestion
- host the [Docker image of the project](https://cloud.docker.com/u/knplabs/repository/docker/knplabs/trello-history-powerup)
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +[Github](https://github.com/KnpLabs/trello-history-powerup) !
```suggestion
[GitHub](https://github.com/KnpLabs/trello-history-powerup) !
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
>  8. you table flip the entire open space and think of extreme measures, like
```suggestion
8. you table flip the entire open space and consider extreme measures, like
```

2019-06-29 14:56 UTC, fabschurt commented on trello-history/trello-history.md
> +The second version was done during our last summer Hackathon, and we are pretty
```suggestion
The second version was done during our last summer hackathon, and we are pretty
```

2019-07-01 06:40 UTC, EVDW commented
:+1:

2019-07-01 08:15 UTC, jaljo commented on trello-history/trello-history.md
>  4. you work the hell out of your sweat and blood to get the job done,
:duck:

2019-07-01 08:45 UTC, jaljo commented on trello-history/trello-history.md
> +to build power ups with it. Although their documentation is pretty huge,
sized :)

2019-07-01 08:46 UTC, fabschurt commented on trello-history/trello-history.md
> +to build power ups with it. Although their documentation is pretty huge,
?

2019-07-01 09:13 UTC, merged